# This docker-compose file will assume that encryption/decryption key is available in the present working directory.
# Run ./prepare-env.sh script to create key.
version: "3.9"
services:
  app-receiver:
    build: ./app-receiver
    image: app-receiver:latest
    secrets:
      - decryption_key
    ports:
      - 8080:8080
    volumes:
      - ./output:/usr/src/app-receiver/output
  app-sender:
    build: ./app-sender
    image: app-sender:latest
    secrets:
      - encryption_key
    volumes:
      - ./input/:/usr/src/app-sender/input/
      - ./status-db:/usr/src/app-sender/status-db
secrets:
  decryption_key:
    file: key
  encryption_key:
    file: key