# This docker-compose file will assume that docker swarm is enabled. One node swarm cluster is sufficient to test this.
# 1. First build the images with "docker-compose -f docker-compose-v2.yml build --no-cache".
# 2. Then Run "docker swarm init" to initialize a single node swarm cluster.
# 3. Next run "./create-docker-secret.sh" to create docker secrets to be used with the containers.
# 4. Finally run "docker stack deploy --compose-file docker-compose-v2.yml".
# 5. Verify if services are running healthily.
version: "3.9"
services:
  app-receiver:
    build: ./app-receiver
    image: app-receiver:latest
    secrets:
      - source: app-sender-receiver-key
        target: decryption_key
    ports:
      - 8080:8080
    volumes:
      - ./output/:/usr/src/app-receiver/output/
  app-sender:
    build: ./app-sender
    image: app-sender:latest
    secrets:
      - source: app-sender-receiver-key
        target: encryption_key
    volumes:
      - ./input/:/usr/src/app-sender/input/
      - ./status-db:/usr/src/app-sender/status-db
secrets:
  app-sender-receiver-key:
    external: true