# This docker-compose file will assume that encryption/decryption key is available in the present working directory.
# Run ./prepare-env.sh script to create key.
version: "3.9"
services:
  app-receiver:
    build: ./app-receiver
    volumes:
      - ./output:/usr/src/app-receiver/output
      - ./key:/run/secrets/decryption_key:ro
    image: app-receiver:latest
    ports:
      - 8080:8080
  app-sender:
    build: ./app-sender
    volumes:
      - ./input/:/usr/src/app-sender/input/
      - ./status-db:/usr/src/app-sender/status-db
      - ./key:/run/secrets/encryption_key:ro
    image: app-sender:latest

    
